<?php

class Admin extends User {
    public function __construct($firstName, $lastName, $email, $password, $phoneNumber, $role)
    {
        parent::__construct($firstName, $lastName, $email, $password, $phoneNumber, $role);
    }
    public function signUp($db)
    {
        parent::signUp($db); // TODO: Change the autogenerated stub
    }

    public function manageStudents(){

    }
    public function manageTeachers(){

    }
    public function manageCourses(){

    }
    public function manageTags(){

    }
    public function manageCategorys(){

    }

    public function totalStudents(){


    }

    public function totalTeachers(){

    }

    public function topThreeTeachers(){

    }

    public function changeTeacherStatus(){

    }

    public function topCourse(){

    }

}
?>